// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvbluthegtepwjbhudtu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2Ymx1dGhlZ3RlcHdqYmh1ZHR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMzAxOTMsImV4cCI6MjA2NzgwNjE5M30.7IfOLeNRjTWCD_gEX0ws9ltzqvqWjNFeXl14YrDI4Yo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});